### ISSUE TITLE
Compiling isssue

### ISSUE THREAD

**Issue by j-dbooth** [ryancdotorg/brainflayer#186]
Not sure why the same topic was fully closed before when issue still arise's...

`/mnt/c/Users/Jms/brainflayer$ make
gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainwalletio.o algo/warpwallet.o algo/keccak.o algo/sha3.o algo/brainv2.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lrt -lcrypto -lgmp -lpthread -o brainflayer
/usr/bin/ld: /tmp/brainflayer.IalWQh.ltrans0.ltrans.o: in function `main':
<artificial>:(.text.startup+0x2245): undefined reference to `bloom_chk_hash160'
collect2: error: ld returned 1 exit status
make: *** [Makefile:68: brainflayer] Error 1`

i've already done
`change : 
LIBS = -lssl -lrt -lcrypto -lz -lgmp
 to   : 
LIBS = -lssl -lrt -lcrypto -lz -lgmp -lpthread
and
remove all "-static" like :
$(COMPILE) -static $^ $(LIBS) -o $@
 to
$(COMPILE)  $^ $(LIBS) -o $@ `

Didnt change the issue in anyway, trying to compile using WSL Ubuntu 20.04

**Comment by j-dbooth** [comment]
Nevermind, i downloaded Kali-WSL instead and it compiled just fine for some reason
